Feature/app store version localization
AvdLee/appstoreconnect-swift-sdk pull request #130
Opened 2021-01-29 10:45 UTC by Ikloo

Hi! 

Added support for [AppStore Version Localizations List](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_version_localizations_for_an_app_store_version)

2021-02-01 16:51 UTC, AvdLee requested changes
This looks great! I just have a small addition.

2021-02-01 16:51 UTC, AvdLee commented on Sources/Models/AppStoreVersionLocalizationRelationship.swift
> +//    case appPreviewSet(AppPreviewSet)
Can't we remove these instead?

2021-02-03 11:24 UTC, Ikloo commented on Sources/Models/AppStoreVersionLocalizationRelationship.swift
> +//    case appPreviewSet(AppPreviewSet)
Sure, done

2021-02-03 13:42 UTC, AvdLee commented on Sources/Models/AppStoreVersionLocalizationRelationship.swift
> +            fatalError()
@Ikloo can you take care of this too?

2021-02-03 13:54 UTC, Ikloo commented on Sources/Models/AppStoreVersionLocalizationRelationship.swift
> +            fatalError()
yes, made another solution. Added AppStoreVersion as single case

2021-02-04 09:46 UTC, AvdLee approved these changes
Thanks for going over my feedback!

2021-02-04 09:46 UTC, merged