Adding download on RequestExecutor
AvdLee/appstoreconnect-swift-sdk pull request #133
Opened 2021-03-05 01:15 UTC by barrault01

Hello I think the download of the reports should be through downloadTask instead of a dataTask so I recreate a new method to user downloadTask instead of  dataTask. I was not able to run the tests. Can you helped me run it?

2021-03-05 12:38 UTC, AvdLee requested changes
Thanks, this looks great! I see there are a few new methods regarding downloading. Could you write tests for these?

2021-03-05 12:38 UTC, AvdLee commented on Sources/APIProvider.swift
> +
```suggestion

```

2021-03-05 12:38 UTC, AvdLee commented on Sources/DefaultRequestExecutor.swift
> +
```suggestion

```

2021-03-09 12:22 UTC, barrault01 commented
@AvdLee I remove the extras lines add some tests and put a time zone on the testDateDecoding because it was failing on my computer has I am on an other time zone.

2021-03-10 16:08 UTC, AvdLee approved these changes
Looks all good, thanks a lot!

2021-03-10 16:08 UTC, AvdLee commented on Tests/APIProviderTests.swift
> +        outputFormatter.timeZone = TimeZone(identifier: "GMT")
Perfect!

2021-03-10 16:08 UTC, merged